# 突破 Docker 容器的漏洞验证代码


##### 作者：[James Turnbull](https://twitter.com/kartar) 

##### 译者：[Chris Liu](http://weibo.com/u/5155462294)

***
一直以来我们对于 Docker 安全问题的处理相当谨慎，而且尽量做到透明。今天早上，我们发布了一份关于如何突破 Docker Engine 0.11 容器限制的漏洞利用代码。

 - 需要强调的是，只有在容器内以 root 权限运行不受信任的应用程序，才有可能触发这个漏洞。而这是我们**不推荐的**运行  Docker Engine 的方式。
 - **我们还要明确的是，Docker Engine 1.0 没有这个漏洞隐患**。所以我们强烈推荐用户将 Docker Engine 升级到 1.0 这个更成熟的版本以根除后患并且获得更好的支持。

该漏洞利用验证代码要突破容器，前提条件是进程需要有一个内核的  capability （ Linux 内核的 capability 定义可参见 [FAQ](https://www.kernel.org/pub/linux/libs/security/linux-privs/kernel-2.2/capfaq-0.2.txt) ）。这个内核 capability 允许当前进程根据指定的 inode  打开任何文件。在大多数系统上，根文件系统（/）的 inode 号是2。根据这个 inode 号加上利用这个内核的 capability，容器内的有 root 权限的进程可以打开宿主系统上的根节点然后遍历宿主系统的整个文件系统，读取本应该无权访问的宿主系统上的敏感信息例如用户密码等等。

在早些版本的 Docker Engine  中（0.12以前的版本），新创建的容器会放弃一组特定的内核 capability ，但是会保留其它的所有 capability ，包括上述的 capability。在0.12以及之后一直到目前的1.0版本中，新创建的容器默认会放弃所有的内核 capability。从本质上说，这相当于把内核 capability的继承方式从原来的黑名单方式变成了白名单方式。

今早，我们已经发布了针对这个漏洞的补丁。请记住，在任何情况下我们都不主张在 Docker Engine 的容器中以root权限运行任何的不受信任的程序。 如果你坚持要这样使用 Docker Engine ， 系统的安全性可能会受到一系列众所周知的内核安全漏洞的影响。因此，我们特别建议你：

 - 在运行 Docker Engine 的系统中同时运行 AppArmor 或者 SELinux。
 - 将机器分成不同的组，相互信任的容器划在一组。
 - 不要以 root 权限运行任何不受信任的应用程序。

另外， Docker Engine  在不久的将来将会支持用户态命名空间，为容器提供一套安全管理机制。

我们还想重申我们的安全政策。对于安全漏洞， Docker  支持和遵循 [“ 负责任的漏洞披露 ”( responsible disclosure)](http://en.wikipedia.org/wiki/Responsible_disclosure) 。我们很乐意披露安全漏洞的所有细节，但是希望漏洞发现者在公开发布漏洞细节之前，给我们留出足够的时间来修补漏洞和发布相应的补丁程序。我们也会奖励漏洞研究人员或者报告人。如果你发现任何安全问题，请发邮件报告给 <security@docker.com> 。

请阅读 [这篇文章](http://www.docker.com/resources/security)， 了解 Docker 的最佳安全实践方法。

***

##### 这篇文章由 [James Turnbull](https://twitter.com/kartar) 撰写， [Chris Liu](http://weibo.com/u/5155462294) 翻译。点击 [这里](http://blog.docker.com/2014/06/docker-container-breakout-proof-of-concept-exploit/) 阅读原文。

##### The article was contributed by [James Turnbull](https://twitter.com/kartar), click [here](http://blog.docker.com/2014/06/docker-container-breakout-proof-of-concept-exploit/) to read the original publication.

